---
dist: xenial
language: python
python: 3.7
before_install:
    - sudo apt-get update -qq
    - sudo apt-get install -qq libxml2-utils
install:
    - pip install -r requirements.txt
jobs:
    include:
        - stage: flake8 lint
          script: flake8 --exclude=pyenv,pyenv3 --ignore E501,E731,W504,W503
        - stage: test
          script: ./gen.sh
stages:
    - flake8 lint
    - test
